### ISSUE TITLE
Failed to initialize BMS

### ISSUE THREAD

**Issue by 7wells** [patman15/BMS_BLE-HA#35]
Hello! 

I see a warning after every HA restart, but the readings seem to be ok.

Sorry that it's partly in German, despite I changed the language in several places to English. The BMS number shown below is partly redacted:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bms_ble
Quelle: custom_components/bms_ble/__init__.py:46
Integration: BLE Battery Management (Dokumentation, Probleme)
Erstmals aufgetreten: 20:42:32 (1 Vorkommnisse)
Zuletzt protokolliert: 20:42:32

Failed to initialize BMS x6xx10xx6xx, continuing
```

Do you have an idea for the reason? Shall I simply ignore it, or is there something I should do about it? Shall I add some log file?

Thanks for your help! 👍

**PS:**
The log file ends with this (number partly redacted): 
```
[custom_components.bms_ble] Finished fetching x6xx10xx6xx data in 0.120 seconds (success: True)
```

**Comment by patman15** [comment]
> Do you have an idea for the reason? 

I'm aware of this issue, happens for me as well. I suspect it's an issue with the HA Bluetooth integration not being ready when bms_ble is started. This happens despite the fact that bms_ble has a dependency towards Bluetooth. Probably due to devices not yet being discovered/resolved. Only happens on complete HA restart, if you just restart bms_ble it does not occur.

> Shall I simply ignore it, or is there something I should do about it? Shall I add some log file?

You can safely ignore it. If I'm really bored, I might dig into it at a later point in time. :sunglasses: You shouldn't see any impact except probably a bit delayed first measurements.

**Comment by patman15** [comment]
> Am I right assuming that the following warning is related?

Not sure since I can see `(8 Vorkommnisse)`. Did you restart that often? Or, which I suspect, do you have BT connection issue, i.e. battery is too far away? You could enable the RSSI sensor and monitor that value over a day or so.

The template can be fixed like this:
```Javascript
{{ iif(has_value("sensor.car_battery2_delta_voltage"), state_attr("sensor.car_battery2_delta_voltage", "cell_voltages")[0], "n/a")}}
```
That will show `n/a` when the value is not available and not throw an error.

Enjoy your weekend as well!

**Comment by patman15** [comment]
The signal strength picture shows some unavailable parts (interrupted line). So it looks like you have some BT disturbances around. The message is just a warning that the initial retrieval of data failed. The integration will continue to work normal.
Probably I should downgrade the severity of that message as it is really not that critical, can happen any time. Or I can introduce the retry library to make the connection more robust.
Do you have issues with data availability? I would guess so from the graph. Do you see the same unavailability also in the other values?

**Comment by patman15** [comment]
Sorry for that, I oversaw that the configuration via GUI is limited, try this:
```javascript
{{ iif(has_value("sensor.car_battery2_delta_voltage"), state_attr("sensor.car_battery2_delta_voltage", "cell_voltages")[0], None) }}
```
Difference is only the `None` at the end. This will result in `unknown` instead of `unavailable` which would be correct, but in the end does not matter and for the latter you need to go into the YAML configuration. :wink:

**Comment by patman15** [comment]
> Yes, time and again I see "unavailable" messages from your integration, which is undoubtedly related to my not always good connection. And please accept my apologies that I did not realize this earlier.

No worries, happy to help. I can make a branch to test a version that is a bit more robust to disturbance (does retries) if you want. Nevertheless, when there is no connection (within 30s), you won't get data so not sure it really makes a difference. Let me know your preferences.

**Comment by patman15** [comment]
> If you have time and would like to do this, I am happy to test and report back.

Ok, give me a bit of time, I'll ping you if I have branch. Shouldn't be too complicated.

> Would it be possible and make sense to retain the last value (as with "last will" in MQTT) in case of loss of connection? Maybe not, but I am unsure.

I'm a fan of *separation of concerns* which in this case means, the integration should assume something about the usage, i.e. there might be applications where you want to know if you loose the connection, thus the integration should not hide that. Templating could help in your case again if necessary. But let's see if the more robust version can fix it as well.

> Maybe there are Wifi or BT signals from the neighbourhood or our own that disturb the BT signal 

2.4GHz WiFi is in the same band as Bluetooth, also other Bluetooth devices (like your ESP32) might disturb. Removing thos should definitely enhance the availability.

**Comment by patman15** [comment]
@7wells I made a quick fix for your connection issues that might help. Currently, it only affects the JBD type BMSs. The modifications are in a [feature branch for robustness](https://github.com/patman15/BMS_BLE-HA/tree/feature/retry_for_robustness). Do you know how to install or do you need guidance?

**Comment by patman15** [comment]
Instructions are actually here: https://github.com/patman15/BMS_BLE-HA/tree/feature/retry_for_robustness?tab=readme-ov-file#manual and you just need to get the files from the branch (link you sent is correct).
The folders should already exist if you installed via HACS, so basically replacing the files should do it.

**Comment by patman15** [comment]
Hey, just say ... I can prepare a beta version a bit later today so you can install via HACS. No problem!
--
Touched, not typed.

**Comment by patman15** [comment]
Hi, you can try [v1.6.3_retry](https://github.com/patman15/BMS_BLE-HA/releases/tag/v1.6.3_retry), which should be available via HACS (try `update information`, `redownload`). I do not know why, but the error above looks like an issue with my new German translation which I can't find. In case it persists even after updating via HACS (no idea why), please delete the file `custom_components/bms_ble/translations/de.json` in your local installation and try again.

**Comment by patman15** [comment]
> Shall I help you with the translation? (if needed at all)

Thanks, there is not much to do, only a few sentences and they are done.

> (sorry for "DEnglish")

That's a HA backend issue ...

> What can I do to find out more? Running in debug mode and post a log? 

Unfortunately, debug log won't help much in this case. Tried to debug it myself, BT says connection timed out. :face_with_diagonal_mouth: 

Please try this [version](https://github.com/patman15/BMS_BLE-HA/releases/tag/v1.6.3_exch), I reverted a change.
For some reason the initialization often fails (on unknown criteria) and won't recover. I removed the recovery function because all other BT integrations do not have a similar function, but obviously that was a mistake. :disappointed:

**Comment by patman15** [comment]
And these messages are produced by the `v1.6.3_exch` release you installed and rebooted? You have a type `JBD` BMS, correct? Just checking, because that would mean that HA could not connect to the BMS after 4 retries ...

**Comment by patman15** [comment]
> BTW, when I reload the integration, the entities become available again almost instantly. Would it make sense to auto-reload on disconnection in order to thus try to reconnect?

Hmm, that is also a strange behavior. I do not have much experience with BT proxy, in principle it should be transparent for the integration.

I made a new version, that adds two diagnostic sensor (you need to enable them like the `RSSI` sensor): [v1.6.3_lq](https://github.com/patman15/BMS_BLE-HA/releases/tag/v1.6.3_lq). `Link quality` shows you the percentage of successful queries within the last 100 tries, `link down` the longest duration the BMS was not available (within the last ~hour).
Maybe you can let this version run at least a day and then let's have a look at the graphs. Also you could use it to experiment with your setup to fix the connection issue.
Let me know what you think.

**Comment by patman15** [comment]
Can you post a >=24h graph of the two new sensors?

**Comment by patman15** [comment]
Wild guess, your (solar) charge controller disturbs the BT connection? Just guessing, because during the night everything looks fine, while in the morning there is a serious outage. Maybe the ESPhome proxy reboots?
Also the outage is so long that even my robustness enhancement won't help there. Sorry, running out of ideas otherwise.

**Comment by patman15** [comment]
> Will you make this pre-release an official release? 

I tend to say no, but I'm not sure yet. It's mainly a debugging feature. Anyways, you can stay on the beta for a while because the next release will be just some minor corrections and mainly test coverage enhancements. So no feature changes.

I'm still struggling whether I should or shouldn't remove the message at the beginning "Failed to initialize BMS, continuing."
It seemed that without (which is the default with all other HA integrations!) the initialization got stuck with your bad connection. Or maybe just coincidence? Not sure, maybe I will run some further tests ...

**Comment by patman15** [comment]
Hey @7wells, I played around quite some time with a device and an intentionally _bad_ connection, i.e. RSSI below -86dBm. I was worried because you said in https://github.com/patman15/BMS_BLE-HA/issues/35#issuecomment-2336820689 that even after 10 minutes the system did not proceed to normal operation.
I did notice that when you have the connection established the RSSI can drop a bit more and you still get data while it won't establish a connection. So there some kind of "when it works, it stays" thingy but when it exceeded a level it always connected and never stayed off. In the end I cannot relate the changes I did in [v1.6.3_retry](https://github.com/patman15/BMS_BLE-HA/releases/tag/v1.6.3_retry) to your observation that it did not connect for a long time. In my opinion that was an unfortunate coincidence. Would you agree?
If so, consequently, I would proceed with removing the message `Failed to initialize BMS, continuing.` and the associated behavior (to continue despite a device not being reachable at start-up), which is the default for all HA integrations.

**Comment by patman15** [comment]
JFYI, I have internally prepared a change on the `RSSI` sensor, that will make it also available, when connection to the BMS fails. That way, it is easier to track the `RSSI` because you can also see lower values and not just `unavailable`. I might also add an adapted version of the `link quality` sensor to track connection issues separate to the `RSSI`.

**Comment by patman15** [comment]
@7wells So, I finally came to a satisfying solution for tracking the `link quality` and `RSSI`, you can find it on the [branch for RSSI](https://github.com/patman15/BMS_BLE-HA/tree/feature/rssi) (based on v1.6.4). I will release it in a few weeks with the next version.

**Comment by patman15** [comment]
> I just installed 1.6.4 (via HACS) and restarted HA.
>
For the optimized link quality sensors you need to install [manually](https://github.com/patman15/BMS_BLE-HA/tree/feature/rssi?tab=readme-ov-file#manual) from [branch for RSSI](https://github.com/patman15/BMS_BLE-HA/tree/feature/rssi) by replacing all files from there (and then restart)! Version should be then v1.6.**5** The sensors should help you tracking the availability because they are then independent of the availability of the BMS (which is more difficult). See https://github.com/patman15/BMS_BLE-HA/tree/feature/rssi?tab=readme-ov-file#provided-information for details.

> Then I observed that the integration had a problem during initialisation (code after device and after config_entry redacted)
>
That message stays until the integration is able to reach the BMS at least once. (replacement for the warning in the log ... :wink:)

**Comment by patman15** [comment]
Indeed looks strange, could be a bug in the integration, but without debug logs I'm not able to tell. There were no big changes between v1.6.3 (which had a readout bug) and v1.6.4 (should actually work). But you never know ...

**Comment by patman15** [comment]
@7wells JFYI, I have a ready-made PR that will add new link quality and RSSI sensors in the default release. The PR will close this issue. Feel free to (re)open an/this issue, if you you are still struggling with your setup.

**Comment by patman15** [comment]
It doesn't look like this?
![Bildschirmfoto vom 2024-10-29 13-39-39](https://github.com/user-attachments/assets/3d2cb9bb-b03a-40e5-b4e5-0500e7967bd9)

Maybe I messed up something, but I would need to check that, also whether data is retained needs to be checked. Give me a bit.
`RSSI` "is" the quality of the wireless connection, while the `link quality` is how often the BMS delivered data. So it's related but not the same, see the description.

P.S. please open a question issue for such topics, because I almost missed your comment since this is a closed issue and I usually only watch open ones ...

**Comment by patman15** [comment]
Hi! Still strange. Can you please run with the new version 1.7.1 (I fixed some issues there that might be related) and if it does not help, please open a new issue and attach a debug log so I can check what is happening. Thanks!

**Comment by patman15** [comment]
You can enable debug logging at any point in time (as well as disable it). The only requirement is that you have it enabled when something happens. If you then provide me the log of the relevant time period, I can hopefully say more.

**Comment by patman15** [comment]
The link quality is not ok, as it is 45% and dropping, thus it is also logic that the signal quality is unavailable. RSSI is independently reported from the BMS sensors and also from link quality. I guess that the sensor was available quite some time. To see unavailability you need to look into the developer tools and then click the (i) button to see the graph which is then interrupted most likely.
