### ISSUE TITLE
DALY Smart Active BALANCER - Can't connect

### ISSUE THREAD

**Issue by koogle1** [patman15/BMS_BLE-HA#42]
### Checklist

- [X] I need support with using the integration.
- [X] My issue is not a [feature request](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Feature%2BRequest&projects=&template=feature_request.yml)
- [X] I'm not avoiding to fill out the [bug report](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Bug&projects=&template=bug.yml) form.

### Describe the issue

Hi Patrick.
I am trying to connect this DALY (https://de.aliexpress.com/item/1005004599618728.html) LiPo 15s battery BALANCER to my Home Assistant. I tried (https://github.com/fl4p/batmon-ha) before and it repeatedly connected briefly but then stopped polling the data after a few seconds/readings. I saw timeouts in the logs so it was expecting to receive a larger set of data, i.e. from a true DALY BMS, whereas the BALANCER only delivers some basic data like cells voltages, total voltage, etc. DALY uses the same App though for all devices.
I de-installed "batmon-ha" and added your integration but now I only get the "No devices found on the network" message. I can only assume that this relates to the fact that the device is different to those already known by your program. So I guess I actually have to make this a feature request, right?
My BT-Adapter Log shows the DALY BT-Adapter as seen (no timeout - it's permanently set to ON):
![Screenshot 2024-09-05 155056](https://github.com/user-attachments/assets/27333489-21de-4998-94dd-2f5990d9d02e)

I'm relatively new to HA but learning fast ;-) I'm no programmer but an electrical engineer with lots of programming experience since th early 80s (yes, when so-called "computers" still had HEX keyboards) :-)

So I'll do my best to follow any advice you may have.
Thank you already, hoping to solve this together.
Kind regards,
Ronny

**Comment by patman15** [comment]
Hi Ronny,

first of all, good to here that you are already happy! :smile:  Thanks for confirming my theory on how to pair devices and get it working, that is very good to know.

> But maybe there is a way to find more? It should e.g. be possible to set some switches to enforce the balancing and should be able to show if the balancing is ongoing etc..

The sensors you see are all that the integration provides based on the data coming from the device. I can assure you there are no other (hidden) ones. :wink: Since the intention of this integration was to provide information about the battery status (having BMSs in mind) I did not implement any active / controlling elements, i.e. switches. Also I'm avoiding active influences on a BMS, as such devices are safety relevant, i.e. don't want to be blamed for the integration having destroyed a battery or worse. (Note that the protocols are mostly reverse engineered by community or me).

Let me know if you really think you are missing something really important, then let's discuss. Please bear in mind that I try to keep functionality consistent over all supported devices and a 100% test coverage to ease usage, documentation, and most important: maintenance.
